openapi: 3.0.0
info:
  title: Applications & Compliance
  version: 2.0.0
tags:
  - name: applications
    description: application centric resources
paths:
  /application-types:
    get:
      tags:
        - applications
      summary: List application types
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ApplicationType'
  /application-types/{id}/applications:
    get:
      tags:
        - applications
      summary: List applications by type
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Application'
        '404':
          description: Not found
    parameters:
      - name: id
        in: path
        description: ID of application type to use
        required: true
        schema:
          type: string
  /applications/{id}:
    get:
      tags:
        - applications
      summary: Get a single application 
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Application'
        '404':
          description: Not found
    parameters:
      - name: id
        in: path
        description: ID of application type to use
        required: true
        schema:
          type: string
components:
  schemas:
    ApplicationType:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
    Application:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        reference:
          type: string
          description: Unique reference number
        capabilities:
          type: array
          items:
            $ref: '#/components/schemas/Capability'
    Capability:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
